{
 "title": "Harbor / Overview",
 "tags": [ "harbor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(harbor_health{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(harbor_health{}, job)"
    }
   },
   {
    "name": "ip",
    "label": "ip",
    "query": {
     "query": "label_values(harbor_health{job=\"$job\", instance=\"$instance\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Status Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Harbor Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_health{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chartmuseum Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"chartmuseum\"}"
    }
   ]
  },
  {
   "title": "Core Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"core\"}"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"database\"}"
    }
   ]
  },
  {
   "title": "Jobservice Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"jobservice\"}"
    }
   ]
  },
  {
   "title": "Portal Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"portal\"}"
    }
   ]
  },
  {
   "title": "Redis Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"redis\"}"
    }
   ]
  },
  {
   "title": "Registry Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"registry\"}"
    }
   ]
  },
  {
   "title": "Registryctl Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"registryctl\"}"
    }
   ]
  },
  {
   "title": "Trivy Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"trivy\"}"
    }
   ]
  },
  {
   "title": "F I L L",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "options": {
    "content": "<center><b><font color=\"green\">F I L L</font></b></center>"
   },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"registryctl\"}"
    }
   ]
  },
  { "title": "Project Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Project Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "harbor_project_repo_total{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_project_quota_usage_byte{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_project_quota_byte{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_project_member_total{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_project_artifact_total{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_artifact_pulled{job=\"$job\", instance=\"$instance\"}"
    },
    {
     "expr": "harbor_project_quota_byte{job=\"$job\", instance=\"$instance\"} - harbor_project_quota_usage_byte{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Node status information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$ip.*\"}[1m])) by (instance) * 100)",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$ip.*\"} - node_memory_MemAvailable_bytes{instance=~\"$ip.*\"}) / node_memory_MemTotal_bytes{instance=~\"$ip.*\"} * 100",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "Disk Information",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$ip.*\"}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$ip.*\"}"
    },
    {
     "expr": "node_filesystem_files_free{instance=~\"$ip.*\"}"
    }
   ]
  },
  { "title": "Task Status Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cumulative CPU Usage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "累计 CPU 使用时间"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"} + process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "常驻内存"
    }
   ]
  },
  {
   "title": "Task Waiting Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "harbor_task_queue_latency{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{type}}_latency"
    }
   ]
  },
  {
   "title": "Task Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "harbor_task_scheduled_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "scheduled_total"
    },
    {
     "expr": "harbor_task_queue_size{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{type}}_total"
    }
   ]
  }
 ]
}