{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "role",
    "label": "Cluster Role",
    "query": {
     "query": "query_result(pg_up{postgres_operator_crunchydata_com_cluster=\"$cluster_name\"})"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "query_result(pg_up{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", role=\"$role\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "grafana-singlestat-panel",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_connections{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{postgres_operator_crunchydata_com_cluster=\"$cluster_name\", deployment=\"$deployment\", job=~\"$namespace.*\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{deployment=\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", deployment=~\"$deployment\", state=\"active\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", deployment=~\"$deployment\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", deployment=~\"$deployment\", mode=~\"$mode\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", deployment=~\"$deployment\", state=~\"idle|idle in transaction|idle in transaction (aborted)\", job=~\"$namespace.*\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", deployment=~\"$deployment\", job=~\"$namespace.*\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"} / (pg_stat_database_blks_read{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"} + pg_stat_database_blks_hit{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{deployment=\"$deployment\", datname=~\"$datname\", postgres_operator_crunchydata_com_cluster=\"$cluster_name\", job=~\"$namespace.*\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{deployment=\"$deployment\", datname=~\"$datname\", job=~\"$namespace.*\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  }
 ]
}