{
 "title": "ClusterPlex / Orchestrator",
 "description": "Monitoring dashboard for ClusterPlex deployments",
 "tags": [ "clusterplex" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Workers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(workers_active) by (job)" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(worker_load_cpu) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Rank",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(worker_load_rank) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Job Posters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(job_posters_active) by (job)"
    }
   ]
  },
  {
   "title": "Tasks Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(worker_load_tasks) by (worker_name)",
     "legendFormat": "{{worker_name}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(jobs_succeeded[30d])) by (job)",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(increase(jobs_failed[30d])) by (job)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(jobs_killed[30d])) by (job)",
     "legendFormat": "Cancelled"
    }
   ]
  },
  {
   "title": "Posted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_posted[1d])) by (job)"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jobs_completed[1d])) by (job)"
    }
   ]
  }
 ]
}