{
 "title": "Nextcloud / Overview",
 "description": "Dashboard showing metrics gathered by nextcloud-exporter from an Nextcloud instance.",
 "tags": [ "nextcloud" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nextcloud_up,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Users and Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Status",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_up{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_active_users_daily_total{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_active_users_total{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total File Count",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_files_total{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Nextcloud Up ?",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nextcloud_up{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_users_total{namespace=~\"$namespace\"})",
     "legendFormat": "total ({{instance}})"
    },
    {
     "expr": "sum by(instance) (nextcloud_active_users_total{namespace=~\"$namespace\"})",
     "legendFormat": "active ({{instance}})"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_files_total{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Authorization Errors",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_auth_errors_total{namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Free Space Remaining",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(5*1099511627776) - nextcloud_free_space_bytes{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nextcloud_database_size_bytes{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Disk Space Left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_free_space_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Shares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total Shared Links By Type",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nextcloud_shares_total{type=\"authlink\",namespace=\"$namespace\"}",
     "legendFormat": "authlink"
    },
    {
     "expr": "nextcloud_shares_total{type=\"link\",namespace=\"$namespace\"}",
     "legendFormat": "link"
    },
    {
     "expr": "nextcloud_shares_total{type=\"group\",namespace=\"$namespace\"}",
     "legendFormat": "group"
    },
    {
     "expr": "nextcloud_shares_total{type=\"user\",namespace=\"$namespace\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Federated Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(direction) (nextcloud_shares_federated_total{namespace=~\"$namespace\"})",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Federated Nextcloud Data Exchange Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nextcloud_shares_federated_total{direction=\"received\",namespace=\"$namespace\"}",
     "legendFormat": "recieved"
    },
    {
     "expr": "nextcloud_shares_federated_total{direction=\"sent\",namespace=\"$namespace\"}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Shares by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (nextcloud_shares_total{namespace=~\"$namespace\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Installed Apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_installed_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_updates_available_total{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Environment Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Nextcloud Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_system_info{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PHP Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_php_info{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_exporter_info{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases (all instances)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type, version) (nextcloud_database_info{namespace=~\"$namespace\"})",
     "legendFormat": "{{type}} {{version}}"
    }
   ]
  },
  {
   "title": "PHP Max Upload File Size",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 49 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "PHP Max Memory Size",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 49 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_php_memory_limit_bytes{namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}